export interface Sport {
  idLeague: string;
  strDivision: string;
  strCurrentSeason: string;
  strBadge: string;
  strBanner: string;
  strLeague: string;
  strSport: string;
  strCountry: string;
  dateFirstEvent: string;
  strDescriptionEN: string;
  strFanart1: string;
  strFanart2: string;
  strFanart3: string;
  strFanart4: string;
  strGender: string;
  strLogo: string;
  strPoster: string;
  strTrophy: string;
  strWebsite: string;
  strFacebook: string;
  strTwitter: string;
  strYoutube: string;
  idCup: string;
  intFormedYear: string;
  strLeagueAlternate: string;
  strTeam?: string;
  uid?: string;
}
